version: '3'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  checky-api-server:
    image: simmigyeong/prompter-server
    container_name: checky-api-server
    build:
      context: './'
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis

  dcrt-api-server:
    image: simmigyeong/dcrt-server
    container_name: dcrt-api-server
    build:
      context: './
      dockerfile: Dockerfile
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - redis

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - checky-api-server
      - dcrt-api-server